

POST http://localhost:3001/addpost
Content-Type: application/json

{
    "id": 11,
    "image": "https://res.cloudinary.com/dmquudoki/image/upload/v1716304356/2_afjlhh.jpg",
    "description": "bonaks",
    "date": "2024-05-19",
    "user_name": "ROY",
    "user_img": "https://res.cloudinary.com/dmquudoki/image/upload/v1723607507/ttamuytkcopoxzps3qbh.jpg",
    "timePosted": "16:30"
}